### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message

### ISSUE THREAD

**Issue by maxmas** [Apen/googlekeywordsrank#2]
Hello,
I got problem.

Fatal error: Uncaught exception 'Exception' with message 'Google results parse problem : could not find the html result code ' in 
C:\AppServ\www\googlekeywordsrank\GoogleKeywordsRank.php:108 Stack trace: #0 
C:\AppServ\www\googlekeywordsrank\GoogleKeywordsRank.php(130): GoogleKeywordsRank->getKeywordsRank('typo3') #1 
C:\AppServ\www\googlekeywordsrank\index.php(16): GoogleKeywordsRank->getKeywordsArrayRank(Array) #2 {main} thrown in 
C:\AppServ\www\googlekeywordsrank\GoogleKeywordsRank.php on line 108

**Comment by Higure** [comment]
Hey,

This message "Google results parse problem : could not find the html result code" tells you that he can't find this page :
http://www.google.com/search?hl=fr&q=[YourKeywordsHere]

Check out if you have access to Internet when you use the script

Which keywords are you searching for ?

**Comment by Apen** [comment]
Hi,

I modify the script to be more flexible with the html structure. It will now work, check my last commit

**Comment by maxmas** [comment]
Hi,
I try the update. It is work properly.
Thanks!!

And I have question, Google, Bing, Yahoo....  whether the search engine will provide API? 
Which can let people get the keywords rank.
Or we need use this way to get the result.
Through the script pretend that we are a user query, then analyzed the results to determine the ranking position.
