### ISSUE TITLE
Google html structure changed.

### ISSUE THREAD

**Issue by maxmas** [Apen/googlekeywordsrank#3]
Today I found that google has changed the structure of html.
The rank is not correct.
Example: use google browser to search "typo3", $extension ="fr", and check "www.typo3-formhandler.com".
You will find it is rank 23.
But use your script, and setMaxPages(10)... you will find no result.
search Chinese keyword "網站製作", $extension ="com.tw", and check "www.web-propage.com".
You will find it is rank 5.
But use your script, it is show rank 64.

**Comment by Apen** [comment]
Use a browser and request from a script is different.

Google check informations in your google account to modify your search results.
From a script, this is not the case.

Test the script today, it works
